### Register a New User
POST http://127.0.0.1:8000/auth/register/
Content-Type: application/json

{
    "username": "soral",
    "email": "soral11045@mowline.com",
    "password": "1234"
}

###

### Login with Credentials
POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

{
    "email": "soral11045@mowline.com",
    "password": "1234"
}

###

### Access User Profile
GET http://127.0.0.1:8000/auth/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NzAxOTI5LCJpYXQiOjE3MzQ3MDE2MjksImp0aSI6ImM5NmQ0NjcwMmUzYjQxMDNiNGE3MzkzZjE4MmM1MTk5IiwidXNlcl9pZCI6MTF9.gDJ3Wb0ujeSVjmoOySF_DXlO-4_hzVdnAV9gr0CGUiY

###

### Invalid Login Attempt
POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

{
    "email": "wronguser@example.com",
    "password": "WrongPassword123"
}

### Logout
POST http://127.0.0.1:8000/auth/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NzAyNjU5LCJpYXQiOjE3MzQ3MDIzNTksImp0aSI6Ijc5MjU0ZjI0MTIyMzQ1MzhiOTUwZjNkYjljNTE5ZmRhIiwidXNlcl9pZCI6MTF9.2YiPk4VVdK6JIvTIkYU2DQ45Js8QsAZUhT1pxRag6uY
{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNDc4ODc1OSwiaWF0IjoxNzM0NzAyMzU5LCJqdGkiOiIzYzNkN2MxOGU5ZDU0OGYxYTk3NWU2MjQ5MjY3ODk2YiIsInVzZXJfaWQiOjExfQ.kmmf9ob12FtqhDT7qgf4Vht--k5iEOcL-4lUBsb5YXs"
}

