# Generated by Django 5.1.4 on 2024-12-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
