# Generated by Django 5.1.4 on 2024-12-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0004_customuser_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_seller',
        ),
    ]
