from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    OrderViewSet,
    OrderItemCreateView,
    OrderStatusHistoryListView
)

router = DefaultRouter()
router.register(r'orders', OrderViewSet)

urlpatterns = [
    path('', include(router.urls)),  # Include the URLs generated by the router
    path('orders/<int:order_id>/items/',
         OrderItemCreateView.as_view(), name='order-item-create'),
    path('orders/<int:order_id>/status-history/',
         OrderStatusHistoryListView.as_view(), name='order-status-history-list'),
]
